-- Set up RLS policies for all tables
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;

ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

ALTER TABLE certificates ENABLE ROW LEVEL SECURITY;

ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;

ALTER TABLE blog_categories ENABLE ROW LEVEL SECURITY;

ALTER TABLE blog_comments ENABLE ROW LEVEL SECURITY;

ALTER TABLE skin_analyses ENABLE ROW LEVEL SECURITY;

ALTER TABLE ai_recommendations ENABLE ROW LEVEL SECURITY;

ALTER TABLE virtual_tryons ENABLE ROW LEVEL SECURITY;

ALTER TABLE provider_schedules ENABLE ROW LEVEL SECURITY;

ALTER TABLE provider_breaks ENABLE ROW LEVEL SECURITY;

ALTER TABLE booking_reminders ENABLE ROW LEVEL SECURITY;